############################################################
# 03_reference_sample_integration.R
#
# Purpose:
#   Compare probability + non-probability sample integration
#   methods using the simulated scenarios created in:
#
#   scripts/01_simulate_population.R
#
# This script moves beyond the ideal full-population-X setting.
# It uses the probability sample as a reference sample to adjust
# the non-probability sample.
#
# Input:
#   - p-sample  : rows where probability_sample == 1
#                 Variables: X (age, female, higher_education, urban),
#                            design weight d (= N / n_prob under SRS),
#                            Y available as design-based benchmark
#
#   - np-sample : rows where nonprob_sample == 1
#                 Variables: X, Y
#
# Methods:
#   1. Probability-sample mean          -- design-based benchmark
#   2. Naive nonprobability mean        -- unadjusted np-sample mean
#   3. Calibrated np estimator          -- calibrate np weights to p-sample-estimated population totals
#   4. Sample-membership IPW            -- propensity model: P(np | X) pooled over both samples
#   5. Mass imputation to p-sample      -- outcome model fitted in np-sample, predict to p-sample
#   6. Doubly robust integration        -- combine (4) and (5)
#
# Output:
#   - outputs/tables/integration_comparison.csv
############################################################


# -----------------------------
# 0. Load data
# -----------------------------


simulated_scenarios <- readRDS("data/processed/simulated_samples.rds")


# -----------------------------
# 1. Helper functions
# -----------------------------

clip_probabilities <- function(p, lower = 0.001, upper = 0.999) {
  pmin(pmax(p, lower), upper)
}

weighted_mean <- function(y, w) {
  sum(w * y, na.rm = TRUE) / sum(w, na.rm = TRUE)
}

make_x_matrix <- function(data) {
  model.matrix(
    ~ age + female + higher_education + urban,
    data = data
  )
}


# -----------------------------
# 2. Estimator functions
# -----------------------------

# Method 1: Design-based probability-sample mean
#
# Under SRS with equal inclusion probabilities, the design-weighted
# mean is equivalent to the simple sample mean.
prob_sample_mean <- function(p_sample) {
  mean(p_sample$y)
}


# Method 2: Naive nonprobability mean
#
# This is the unadjusted mean from the non-probability sample.
np_naive_mean <- function(np_sample) {
  mean(np_sample$y)
}


# Method 3: Calibrated nonprobability estimator
#
# Calibrate np-sample base weights (all = 1) so that weighted
# X-totals match the p-sample-estimated population X-totals.
#
# In scripts/02_estimate_methods.R, calibration used true
# full-population totals. Here, the target totals are estimated
# from the probability reference sample:
#
#   X_hat_U = sum_{i in s_p} d_i X_i
#
# where d_i is the probability-sample design weight.
#
# Since the p-sample is generated by SRS in this simulation:
#
#   d_i = N / n_p
#
# In real applications, d_i would come from the probability
# survey design.
calibrated_integration_mean <- function(p_sample, np_sample, population_size) {

  x_np <- make_x_matrix(np_sample)
  x_p  <- make_x_matrix(p_sample)

  # Estimated population totals from p-sample design weights
  p_design_weight <- rep(population_size / nrow(p_sample), nrow(p_sample))
  target_totals <- colSums(x_p * p_design_weight)

  # Base weights for np-sample
  base_weights <- rep(1, nrow(np_sample))
  sample_totals <- colSums(x_np * base_weights)

  # Linear calibration:
  #   w_i = d_i * (1 + x_i' lambda)
  #
  # Here d_i = 1 for np-sample units.
  xtx <- t(x_np) %*% x_np
  difference <- target_totals - sample_totals

  lambda <- tryCatch(
    solve(xtx, difference),
    error = function(e) rep(NA_real_, ncol(x_np))
  )

  if (any(is.na(lambda))) {
    return(
      list(
        estimate = NA_real_,
        min_weight = NA_real_,
        max_weight = NA_real_,
        sum_weight = NA_real_
      )
    )
  }

  calibration_factors <- as.vector(1 + x_np %*% lambda)
  calibrated_weights <- base_weights * calibration_factors

  # If calibration is successful, sum(calibrated_weights) should be
  # close to target_totals["(Intercept)"], which estimates N.
  #
  # We use a ratio mean estimator for numerical stability.
  estimate <- weighted_mean(np_sample$y, calibrated_weights)

  list(
    estimate   = estimate,
    min_weight = min(calibrated_weights),
    max_weight = max(calibrated_weights),
    sum_weight = sum(calibrated_weights)
  )
}


# Method 4: Sample-membership IPW
#
# Pool p-sample and np-sample. Define:
#
#   R = 1 if unit is from np-sample
#   R = 0 if unit is from p-sample
#
# Fit:
#
#   P(R = 1 | X)
#
# on the pooled data.
#
# The p-sample provides the reference X distribution.
# The np-sample provides observed Y.
#
# For np-sample units, construct inverse-odds weights:
#
#   w_i = (1 - pi_hat_i) / pi_hat_i
#
# where:
#
#   pi_hat_i = P(R = 1 | X_i)
#
# These weights reweight the np-sample toward the p-sample's
# reference X distribution.
#
# We use a normalized / Hajek-style weighted mean for stability.
membership_ipw_mean <- function(p_sample, np_sample) {

  pooled <- rbind(
    data.frame(
      p_sample[, c("age", "female", "higher_education", "urban")],
      R = 0
    ),
    data.frame(
      np_sample[, c("age", "female", "higher_education", "urban")],
      R = 1
    )
  )

  membership_model <- glm(
    R ~ age + female + higher_education + urban,
    data = pooled,
    family = binomial()
  )

  pi_hat_pooled <- predict(membership_model, type = "response")
  pi_hat_pooled <- clip_probabilities(pi_hat_pooled)

  # Extract predicted membership probabilities for np-sample units.
  # np rows are placed after p rows in the pooled data.
  np_idx <- (nrow(p_sample) + 1):nrow(pooled)
  pi_hat_np <- pi_hat_pooled[np_idx]

  inverse_odds_weights <- (1 - pi_hat_np) / pi_hat_np

  estimate <- weighted_mean(np_sample$y, inverse_odds_weights)

  list(
    estimate = estimate,
    min_weight = min(inverse_odds_weights),
    max_weight = max(inverse_odds_weights),
    sum_weight = sum(inverse_odds_weights)
  )
}


# Method 5: Mass imputation to p-sample
#
# Fit an outcome model E(Y | X) in the np-sample.
# Predict Y for every unit in the p-sample.
# Average predictions using the p-sample design weights.
#
# Under SRS, the design-weighted mean equals the simple mean.
mass_imputation_integration_mean <- function(p_sample, np_sample) {

  outcome_model <- lm(
    y ~ age + female + higher_education + urban,
    data = np_sample
  )

  y_hat_p <- predict(outcome_model, newdata = p_sample)

  estimate <- mean(y_hat_p)

  return(estimate)
}


# Method 6: Doubly robust integration
#
# Combines:
#   - mass imputation / outcome prediction
#   - sample-membership IPW residual correction
#
# Interpretation:
#
#   DR = prediction on p-sample
#        + membership-weighted residual correction from np-sample
#
# First component:
#
#   Fit m_hat(X) = E(Y | X) in the np-sample.
#   Predict Y for the p-sample.
#   Take the p-sample mean of predicted Y.
#
# Second component:
#
#   In the np-sample, compute residuals:
#
#      Y_i - m_hat(X_i)
#
#   Then reweight residuals using inverse-odds membership weights.
#
# We use a normalized / Hajek-style residual correction for stability.
doubly_robust_integration_mean <- function(p_sample, np_sample) {

  # Outcome model fitted in np-sample
  outcome_model <- lm(
    y ~ age + female + higher_education + urban,
    data = np_sample
  )

  m_hat_p  <- predict(outcome_model, newdata = p_sample)
  m_hat_np <- predict(outcome_model, newdata = np_sample)

  prediction_component <- mean(m_hat_p)

  # Membership model fitted in pooled p + np data
  pooled <- rbind(
    data.frame(
      p_sample[, c("age", "female", "higher_education", "urban")],
      R = 0
    ),
    data.frame(
      np_sample[, c("age", "female", "higher_education", "urban")],
      R = 1
    )
  )

  membership_model <- glm(
    R ~ age + female + higher_education + urban,
    data = pooled,
    family = binomial()
  )

  pi_hat_pooled <- predict(membership_model, type = "response")
  pi_hat_pooled <- clip_probabilities(pi_hat_pooled)

  np_idx <- (nrow(p_sample) + 1):nrow(pooled)
  pi_hat_np <- pi_hat_pooled[np_idx]

  inverse_odds_weights <- (1 - pi_hat_np) / pi_hat_np

  residuals_np <- np_sample$y - m_hat_np

  residual_correction <- weighted_mean(residuals_np, inverse_odds_weights)

  estimate <- prediction_component + residual_correction

  list(
    estimate = estimate,
    prediction_component = prediction_component,
    residual_correction = residual_correction,
    min_weight = min(inverse_odds_weights),
    max_weight = max(inverse_odds_weights),
    sum_weight = sum(inverse_odds_weights)
  )
}


# -----------------------------
# 3. Run one scenario
# -----------------------------

integrate_one_scenario <- function(scenario_name, population) {

  population_size <- nrow(population)

  p_sample  <- population[population$probability_sample == 1, ]
  np_sample <- population[population$nonprob_sample == 1, ]

  if (nrow(p_sample) == 0) {
    stop("Probability sample is empty.")
  }

  if (nrow(np_sample) == 0) {
    stop("Non-probability sample is empty.")
  }

  true_mean <- mean(population$y)

  # Optional diagnostic:
  # The p-sample and np-sample are generated independently from
  # the same finite population, so overlap is possible and retained
  # as source-specific observations.
  overlap_n <- sum(
    population$probability_sample == 1 &
      population$nonprob_sample == 1
  )

  # Estimators
  calib_result <- calibrated_integration_mean(
    p_sample = p_sample,
    np_sample = np_sample,
    population_size = population_size
  )

  membership_ipw_result <- membership_ipw_mean(
    p_sample = p_sample,
    np_sample = np_sample
  )

  mass_imp_result <- mass_imputation_integration_mean(
    p_sample = p_sample,
    np_sample = np_sample
  )

  dr_result <- doubly_robust_integration_mean(
    p_sample = p_sample,
    np_sample = np_sample
  )

  results <- data.frame(
    scenario = scenario_name,
    aux_quality = unique(population$aux_quality),
    selection_mechanism = unique(population$selection_mechanism),
    method = c(
      "population_truth",
      "prob_sample_mean",
      "np_naive_mean",
      "calibrated_integration",
      "membership_ipw",
      "mass_imputation_integration",
      "doubly_robust_integration"
    ),
    estimate = c(
      true_mean,
      prob_sample_mean(p_sample),
      np_naive_mean(np_sample),
      calib_result$estimate,
      membership_ipw_result$estimate,
      mass_imp_result,
      dr_result$estimate
    ),
    true_mean = true_mean,
    n_population = population_size,
    n_prob_sample = nrow(p_sample),
    n_nonprob_sample = nrow(np_sample),
    n_overlap = overlap_n,
    min_weight = c(
      NA,
      NA,
      NA,
      calib_result$min_weight,
      membership_ipw_result$min_weight,
      NA,
      dr_result$min_weight
    ),
    max_weight = c(
      NA,
      NA,
      NA,
      calib_result$max_weight,
      membership_ipw_result$max_weight,
      NA,
      dr_result$max_weight
    ),
    sum_weight = c(
      NA,
      NA,
      NA,
      calib_result$sum_weight,
      membership_ipw_result$sum_weight,
      NA,
      dr_result$sum_weight
    ),
    dr_prediction_component = c(
      NA,
      NA,
      NA,
      NA,
      NA,
      NA,
      dr_result$prediction_component
    ),
    dr_residual_correction = c(
      NA,
      NA,
      NA,
      NA,
      NA,
      NA,
      dr_result$residual_correction
    )
  )

  results$bias <- results$estimate - results$true_mean
  results$absolute_bias <- abs(results$bias)

  return(results)
}


# -----------------------------
# 4. Run all scenarios
# -----------------------------

integration_results <- do.call(
  rbind,
  lapply(names(simulated_scenarios), function(scenario_name) {
    integrate_one_scenario(
      scenario_name = scenario_name,
      population = simulated_scenarios[[scenario_name]]
    )
  })
)


# -----------------------------
# 5. Save and print results
# -----------------------------

write.csv(
  integration_results,
  file = "outputs/tables/integration_comparison.csv",
  row.names = FALSE
)

